### ISSUE TITLE
drop() callback not working with images

### ISSUE THREAD

**Issue by mikima** [processing/p5.js#4103]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] DOM

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version:v0.10.2 October 14, 2019
- Web browser and version: 77.0.3865.120 (Official Build) (64-bit)
- Operating System: MacOSX Catalina

- Steps to reproduce this:
Trying to run this example: https://p5js.org/examples/dom-drop.html

```javascript
function setup() {
  // create canvas
  const c = createCanvas(710, 400);
  background(100);
  // Add an event for when a file is dropped onto the canvas
  c.drop(gotFile);
}

function draw() {
  fill(255);
  noStroke();
  textSize(24);
  textAlign(CENTER);
  text('Drag an image file onto the canvas.', width / 2, height / 2);
  noLoop();
}

function gotFile(file) {
  // If it's an image file
  if (file.type === 'image') {
    // Create an image DOM element but don't show it
    const img = createImg(file.data).hide();
    // Draw the image onto the canvas
    image(img, 0, 0, width, height);
  } else {
    console.log('Not an image file!');
  }
}
```
Everything is working, but the image is not placed on the canvas.

I think is something related to the fact that `image()` is called before the image is fully loaded, indeed if I change the code in this way it works:

```javascript
let img;

function setup() {
  // create canvas
  const c = createCanvas(710, 400);
  background(100);
  // Add an event for when a file is dropped onto the canvas
  c.drop(gotFile);
}

function draw() {
  fill(255);
  noStroke();
  textSize(24);
  textAlign(CENTER);
  text('Drag an image file onto the canvas.', width / 2, height / 2);
  noLoop();
  if(img){
    image(img, 0, 0, width, height);
  }
}

function gotFile(file) {
  // If it's an image file
  if (file.type === 'image') {
    // Create an image DOM element but don't show it
    img = createImg(file.data).hide();
    // Draw the image onto the canvas
    // image(img, 0, 0, width, height);
  } else {
    console.log('Not an image file!');
  }
}
```
I don't know if I'm missing something, if is an intended feature or a bug.

The `createFileInput()` function is anyway working.

**Comment by stalgiag** [comment]
Thanks for reporting the bug!

You are right that this is because `image()` is called before the image is loaded. This can also be fixed by placing `image()` inside the `successCallback` parameter of `createImg()` like this:
```js
function gotFile(file) {
  // If it's an image file
  if (file.type === 'image') {
    // Create an image DOM element
    let img = createImg(file.data, () => {
      // Draw the image onto the canvas
      image(img, 0, 0, width, height);
      img.hide();
    });
  } else {
    console.log('Not an image file!');
  }
}
```

**Comment by mikima** [comment]
@stalgiag the `successCallback` of `image()` won't pass back the image itself, is it right?
If, for example, i want to move out the function:
```javascript
function gotFile(file) {
  // If it's an image file
  if (file.type === 'image') {
    // Create an image DOM element
    let img = createImg(file.data, showImage);
  } else {
    console.log('Not an image file!');
  }
}
function showImage(_img) {
  // Draw the image onto the canvas
  image(_img, 0, 0, width, height);
  _img.hide();
  }
}
```

**Comment by stalgiag** [comment]
@mikima No there is no argument passed to the callback as of now. [This is where the callback is called.](https://github.com/processing/p5.js/blob/master/src/dom/dom.js#L423)

**Comment by SachinVarghese** [comment]
@stalgiag @mikima I did have the same issue for my project and had edited the callback as needed. 
So I thought it would be a great time to contribute back and I have submitted a PR that works for me. Can you please review the updates?

**Comment by mikima** [comment]
Hi @SachinVarghese , thank you! I think it's very useful even if I think it doesn't solve the original issue related to `drop()` function: in the previous version of p5 it waited for the end of data loading while now it won't.

**Comment by SachinVarghese** [comment]
Hi, @mikima Can you please explain the issue with the `drop()` function with the new updates? I may have misunderstood the issue here.

**Comment by mikima** [comment]
In the previous version of P5, as described in the documentation, you wouldn't need aadditional callback function, and you should be able to use `image()` directly in the `drop()` callback function. Below code comes from documentation and now is no more working:

```javascript
function gotFile(file) {
  // If it's an image file
  if (file.type === 'image') {
    // Create an image DOM element but don't show it
    const img = createImg(file.data).hide();
    // Draw the image onto the canvas
    image(img, 0, 0, width, height);
  } else {
    console.log('Not an image file!');
  }
}
`

**Comment by SachinVarghese** [comment]
@mikima This example code will not work every time as the loading of the image from the source is asynchronous. And that is the reason to introduce this success callback if I am not wrong. You can use the callback  as follows with the new PR,
```
createImg(file.data,function(img){
    image(img, 0, 0, width, height)
    img.hide();
});
```
Also I think we will have to update the example in the documentation.
@outofambit  @stalgiag  Please share your ideas.
