### ISSUE TITLE
Latest release makes using p5.js in Bower impossible

### ISSUE THREAD

**Issue by rish** [processing/p5.js#823]
From the latest release with this commit:

https://github.com/processing/p5.js/commit/ba817e5c500f24040411cad23cafeaa9f2e81910

There is no p5.js in the lib directory which means I cannot import the file using Bower.

Using Bower was my interim workaround due to p5.js being incompatible with Browserify (see #818).

The Browserify issue was broken with the release prior to the latest one.

I understand you would like to remove all the distributed sources from the lib directory so may I suggest to create a separate repo for the use of Bower that only contains which should have been inside the lib directory.

Thanks.

**Comment by lmccart** [comment]
I'm afraid it's a bit too much overhead for me to maintain a separate repo just holding the lib files, pushing out a new release already involves a lot of individual tasks. Hopefully the fix for #818 will make the bower workaround unnecessary.

**Comment by rish** [comment]
Ok thank you anyway, I could probably set up a separate repo that will automatically build the bower packages on each release, but I thought I'd give you guys first dibs on the idea.

**Comment by kadamwhite** [comment]
@lmccart jQuery includes the built files in their release tags: *e.g.* https://github.com/jquery/jquery/commit/f9846aec1dadc4bc80ca2df47d3ecc1b9f7a4f84 I'll ping @gnarf to see if I can get any insight into how we might be able to replicate their (automated) deploy process to accomplish this manually in the short-term, but since it seems possible I think we should find a way to get the build lib/ files into the released versions of the code.

**Comment by rish** [comment]
@kadamwhite agreed, that would be super useful!

As for a reference, jQuery has a separate dist repo for their release builds, see here for the bower file:

https://github.com/jquery/jquery-dist/blob/master/bower.json

Also the reasoning for stripping out the builds from the lib directory starts from here:

#774

**Comment by gnarf** [comment]
I'm still afk Mon, but jQuery/jquery-release is where the release is defined

**Comment by rish** [comment]
Hi @gnarf I appreciate the response.

The jquery-release repo doesn't have a bower.json to determine where bower should grab the relevant files from.

I'm under assumption that the jQuery team have created a new repo called jquery-dist solely for package managers in preparation for their 3.0.0 release.

This whole process could be put into the current p5.js repo to populate the dist repo automatically, but from my understanding, the release relevant tasks were stripped out from the Gruntfile as they were redundant at the time.

**Comment by kadamwhite** [comment]
I had an interesting conversation today in IRC with some members of the jQuery team (@scottgonzalez, @mzgol, @arschmitz) in order to better understand their process. The log of the discussion is available here: http://irc.jquery.org/%23jquery-dev/default_%23jquery-dev_20150729.log.html#t10:35:14

The summary is that there have been two ways that jQuery releases were tagged and bagged:

- The old way was that for each release, the code would be tagged on a detached head (so the tag would not be a core part of master), and that detached head commit would have the built files added. Advantage: **No separate repo needed, all released builds accessible via tags.** Disadvantage: **Increases the size of the repo with each release, since the built files don't diff incrementally.**
- The new way (for 3.0) is as @rish indicated: they will be releasing to a new repository that will contain only the released code. Advantage: **Does not increase the file size of the core repository, and permits jQuery to maintain separate compat and modern releases with the same version number** (not relevant to us). Disadvantage: **Requires us to maintain a separate -dist repo.**

With the detached head option, each release would *[as I understand it]* then look like this:

- When a release is ready, increment & commit the version number bump,
- checkout the current commit as a detached head,
- run the build task to generate the `/lib/*.js` files,
- commit those built files,
- tag that commit as the release and push up the semver tag,
- Release to NPM (doesn't depend on the tag, just uses the files you tell it to send up),
- Bower should then pick up the tag and be happy

With the separate repo option, it would look like this:

- When a release is ready, build the files,
- copy all distribution files to the release repo,
- tag and push that release
- release to NPM

Both of these can be automated to some extent

**Comment by arschmitz** [comment]
@kadamwhite for publishing to a separate repo there is no need to copy anything. You could still just do it on a detached head, and add the dist repo as another remote in git. Then push the detached head to that remote.

it's kind of a middle ground you have the same basic work flow but you don't bloat the repo. But you still have the disadvantage of maintaining 2 repos.

**Comment by sarahgp** [comment]
The separate repo flow seems to require knowing less about git & have fewer steps, so I normally would advocate for that, just to keep the required skill level for contributors lower. At the same time, really only a few people (or one) is going to be responsible for new releases, so it may not matter. These are my two, prevaricating, cents

**Comment by lmccart** [comment]
Thanks @kadamwhite for researching this and to the jQuery team for your advice. After thinking about it for a while, I think I could go either way (2 repos vs detached head), but I have some preference for keeping the repo size smaller since it seems hard to go back on this.

**Comment by mwcz** [comment]
I just ran into this.  I noticed that even though bower.json says `"main": "lib/p5.min.js"`, and lib/p5.min.js no longer exists, p5.js and p5.min.js do both still exist inside `docs/js/`.  A really quick fix would be to set `"main": "docs/js/p5.min.js"`.  Not the most clean, but very easy.  Thoughts?

**Comment by lmccart** [comment]
good thought, however, this file isn't regularly updated, it's mostly used for local testing. I think the separate releases repo makes sense, I just haven't had time to set it up and automate yet. hoping to get to this soon.

**Comment by SangSatori** [comment]
Not being able to use Bower distribution of the library irks me as well. Right now I have a Gulp task for setting up and running Grunt tasks to compile P5.js as in [this Gist](https://gist.github.com/SangSatori/c97b8e4399043f8789a0).

**Comment by lmccart** [comment]
ugh sorry i haven't gotten to this one yet, it's at the top of my todo list!

**Comment by mwcz** [comment]
Great to hear!  In my own fork I'm using the quick fix I mentioned above, but really looking forward to the real thing.

**Comment by lmccart** [comment]
ok built files from new releases are now updated here: https://github.com/lmccart/p5.js-release.
however, I'm not much of a bower pro. can someone that understands that system better take a look at bower.json and update anything necessary?

**Comment by mwcz** [comment]
awesome!  thank you!

I'm not a Bower expert but I think that because the bower package named 'p5js' is currently registered for the `git://github.com/lmccart/p5.js.git` repo, you'll need to unregister it and re-register 'p5js' for `git@github.com:lmccart/p5.js-release.git`.  Here are [bower's instructions](http://bower.io/docs/creating-packages/#register).  Hope that helps.  I haven't done it before myself.  Sorry if you already know all this. :turtle: 

The bower.json looked good to me (but again I'm no expert!) so it should be possible now to `bower install git@github.com:lmccart/p5.js-release.git`.  Once the registration is complete it will be possible to `bower install p5js`.

**Comment by lmccart** [comment]
thanks, that was exactly what I needed. new endpoint is set and I just confirmed it is possible to download with command `bower install p5js`.

**Comment by mzgol** [comment]
Note, though, that if you move the repo that a specific bower package points to (here it's `p5js`) then all the older releases magically disappear which may make a lot of broken installation. We had this problem in jQuery; the unofficial bower repository was publishing built files under `jquery.js` and in our official packages it's under `dist/jquery.js`. To not break current installations for all tags that used to exist in the old repo we added a copy of `dist/jquery.js` at `jquery.js`, see e.g. https://github.com/jquery/jquery/tree/1.10.2

Issues like that are the reason why I avoid using bower in development in all my packages (I keep supporting it in [check-dependencies](https://www.npmjs.com/package/check-dependencies) but that's not for my own purposes anymore).

**Comment by mwcz** [comment]
@lmccart can you think of a reason that I'd be seeing `this._graphics` is undefined while using the new repo?  I did a quick scan of p5.js and saw `this._graphics` referenced, but never initialized.

**Comment by lmccart** [comment]
@mwcz can you confirm you're using version 0.4.12? there was [a bug](https://github.com/processing/p5.js/issues/921) with `this._graphics` in 0.4.11, I just pushed an updated version last night.

**Comment by sepans** [comment]
I was reading this thread just to learn about the release process and I was wondering if it is possible to put lib files along the `bower.json` in a branch, lets say `release`, similar to [release repository](https://github.com/lmccart/p5.js-release), and register that branch with bower.

It should be possible to register a branch as bower github endpoint. Github releases could also be off a branch other than `master`.

This way:
- `master` branch remains small (if `git clone` time is the issue here)
- Everything is more integrated and stays in the same repo.
- Release could be automated by a grunt task using [grunt-github](https://github.com/rubenv/grunt-git)

This was just an ad-hoc idea which now seems so plausible to me that I feel I am missing something. Does that work @kadamwhite?

**Comment by mwcz** [comment]
@lmccart I haven't tested that yet, but I had to share this.  Someone snapped a picture while I was debugging the _graphics issue 

https://instagram.com/p/7tPnGADEQ9/

**Comment by mwcz** [comment]
@lmccart Ahhh, I see what's happening.  It's still not working because in the release repo, tag 0.4.12 actually includes version 0.4.11.  

p5.js from tag 0.4.12, see version number at top of tile: https://github.com/lmccart/p5.js-release/blob/0.4.12/lib/p5.js

I'm getting around it by doing `bower install p5js#master` which works for now but isn't ideal.

**Comment by dhowe** [comment]
haha, nice @mwcz

**Comment by lmccart** [comment]
ah thanks @mwcz! I didn't realize that the release tags needed to be there, I thought updating the file was enough. I'll sort this out tomorrow and make sure tagged releases get published for each version in the future.

**Comment by mwcz** [comment]
Thanks @lmccart!  :+1: :tangerine:

**Comment by mwcz** [comment]
FYI, it looks like tag 0.4.14 in the release repo includes version 0.4.13 of p5 https://github.com/lmccart/p5.js-release/blob/0.4.14/lib/p5.js#L1.

**Comment by karneaud** [comment]
Not sure if this was solved but in trying to install pjs via bower I get


`bower install p5js#master`

> bower not-cached    git://github.com/lmccart/p5.js-release.git#master
> bower resolve       git://github.com/lmccart/p5.js-release.git#master
> bower checkout      p5js#master
> bower invalid-meta  p5.js is missing "ignore" entry in bower.son
> bower resolved      git://github.com/lmccart/p5.js-release.git#479fc0d0a1
> bower ENOTFOUND     Package p5.js not found
>
